Repository fga-eps-mds/2019.1-unbrake, pull requests merged in 2019-04, with the labels that each got.

#46 Adicionar depêndencias faltantes para testes do frontend
  unbrake-frontend/package.json
Labels: devops

#63 Configuracao inicial backend
  .dockerignore
  .gitignore
  .travis.yml
  docker-compose.yml
  unbrake-api/Dockerfile
  unbrake-api/configuration/__init__.py
  unbrake-api/configuration/admin.py
  unbrake-api/configuration/apps.py
  unbrake-api/configuration/migrations/__init__.py
  unbrake-api/configuration/models.py
  unbrake-api/configuration/test_models.py
  unbrake-api/configuration/views.py
  unbrake-api/manage.py
  unbrake-api/pytest.ini
  unbrake-api/requirements.txt
  unbrake-api/scripts/entrypoint.dev
  unbrake-api/secrets/API_DJANGO_SECRET_KEY.enc
  unbrake-api/unbrake_api/__init__.py
  unbrake-api/unbrake_api/settings.py
  unbrake-api/unbrake_api/urls.py
  unbrake-api/unbrake_api/wsgi.py
  unbrake-frontend/Dockerfile
  unbrake-frontend/scripts/host_hook_template
Labels: devops

#66 Configurar ferramentas de checkagem do backend
  .travis.yml
  docker-compose.yml
  unbrake-api/.flake8
  unbrake-api/.pylintrc
  unbrake-api/Dockerfile
  unbrake-api/configuration/__init__.py
  unbrake-api/configuration/admin.py
  unbrake-api/configuration/apps.py
  unbrake-api/configuration/models.py
  unbrake-api/configuration/test_models.py
  unbrake-api/configuration/views.py
  unbrake-api/hooks/pre-commit
  unbrake-api/hooks/pre-push
  unbrake-api/manage.py
  unbrake-api/requirements.txt
  unbrake-api/scripts/check
  unbrake-api/scripts/run_container_hook
  unbrake-api/scripts/scripts_environments
  unbrake-api/unbrake_api/settings.py
  unbrake-frontend/Dockerfile
  unbrake-frontend/hooks/host_hook_template
  unbrake-frontend/scripts/host_hook_template
  unbrake-frontend/scripts/run_container_hook
  unbrake/package.json
  unbrake/src/App.js
Labels: devops

#77 Fazer jest falhar em caso de warning ou consoles
  .gitignore
  unbrake-api/Dockerfile
  unbrake-frontend/package.json
  unbrake-frontend/scripts/check_tests
  unbrake-frontend/src/components/SideBarMenu.jsx
  unbrake-frontend/src/tests/App.test.jsx
  unbrake-frontend/src/tests/__snapshots__/Configuration.test.jsx.snap
  unbrake-frontend/src/tests/__snapshots__/Login.test.jsx.snap
  unbrake-frontend/src/tests/__snapshots__/RealTimeChart.test.jsx.snap
Labels: devops, enhancement

#82 Adiciona informações sobre scripts de checagem no README
  README.md
Labels: devops

#87 Conserta bug de checagem via manage.py
  unbrake-api/unbrake_api/management/commands/_script.py
  unbrake-api/unbrake_api/management/commands/check_all.py
  unbrake-api/unbrake_api/management/commands/check_format.py
  unbrake-api/unbrake_api/management/commands/check_lint.py
  unbrake-api/unbrake_api/management/commands/check_tests.py
  unbrake-api/unbrake_api/management/commands/fix.py
  unbrake-frontend/.eslintrc.json
  unbrake-frontend/scripts/check_tests
  unbrake-frontend/src/components/Login.jsx
Labels: bug, devops

#90 Integrar CodeClimate
  .codeclimate.yml
  .travis.yml
  README.md
  docker-compose.yml
  unbrake-api/.coveragerc
  unbrake-api/requirements.txt
  unbrake-api/scripts/check_all
  unbrake-api/scripts/check_tests_coverage
  unbrake-api/scripts/check_tests_coverage_html
  unbrake-api/unbrake_api/management/commands/check_tests_coverage.py
  unbrake-api/unbrake_api/management/commands/check_tests_coverage_html.py
  unbrake-frontend/.eslintignore
  unbrake-frontend/package.json
Labels: devops

#100 Corrigir comandos de execução de checagem
  README.md
Labels: bug

#102 Adiciona arquivos de cobertura de testes aos ignorados do pylint
  unbrake-api/.coveragerc
  unbrake-api/.pylintrc
Labels: bug

#115 Prepara ambiente de produção da API
  production/docker-compose.yml
  unbrake-api/.coveragerc
  unbrake-api/.flake8
  unbrake-api/.pylintrc
  unbrake-api/Dockerfile
  unbrake-api/production/Dockerfile.api
  unbrake-api/production/entrypoint
  unbrake-api/production/nginx.conf
  unbrake-api/production/requirements.txt
  unbrake-api/production/settings.py
  unbrake-frontend/Dockerfile
  unbrake-frontend/scripts/check_tests
Labels: devops

#143 Integra ambientes de produção e homologação ao CI/CD
  .travis.yml
  production/deploy_key.enc
  production/docker-compose.yml
  production/nginx.api.conf
  production/nginx.frontend.conf
  production/secrets/API_DJANGO_SECRET_KEY.enc
  production/secrets/DB_PASSWORD.enc
  scripts/deploy
  scripts/deploy_local.sh
  unbrake-api/production/Dockerfile
  unbrake-api/secrets/DB_PASSWORD.enc
Labels: devops

#140 Ajustando tema do site
  unbrake-frontend/src/App.jsx
  unbrake-frontend/src/components/Login.jsx
  unbrake-frontend/src/components/SignUp.jsx
  unbrake-frontend/src/routes/Routes.jsx
Labels: front-end

#145 Melhorar código do frontend
  unbrake-api/production/settings.py
  unbrake-frontend/src/components/Analysis.jsx
  unbrake-frontend/src/components/CalibrationTempCheck.jsx
  unbrake-frontend/src/components/CalibrationTempFields.jsx
  unbrake-frontend/src/components/CalibrationTempForm.jsx
  unbrake-frontend/src/components/Index.jsx
  unbrake-frontend/src/components/Test.jsx
Labels: front-end
